### ISSUE TITLE
Possible "blank error" being generated

### ISSUE THREAD

**Issue by aarondl** [kat-co/vala#2]
I think that this line is generating a blank error as the first error is appended. It seems unintentional?
https://github.com/kat-co/vala/blob/master/validation.go#L74

It could probably be:
`return &Validation{make([]string, 0, numErrors)}`

That way the memory is allocated for a single element, but no element is actually added. In fact, instead of validationFactory() you could simply use: &Validation{} in it's place, as even if the slice is nil, append will work just fine and create a new slice.

Thanks for the library

**Comment by kat-co** [comment]
Thanks for the PR @aarondl. I'm currently at Gophercon and unable to focus on much, but I'll TAL sometime in the next week or so.
